### PR TITLE
Make compatible with 1.35

### LINKED ISSUE #2: Fatal error: Uncaught Error: Call to undefined function wfSuppressWarnings() in BlueLL
Hi Everyone,

I help run the Crypto++ website and wiki at https://www.cryptopp.com. Our Mediawiki version is 1.34. Also see [Special:Version](https://www.cryptopp.com/wiki/Special:Version).

I attempted to add BlueLL to the skins. Previewing BlueLL results in:

```
Fatal error: Uncaught Error: Call to undefined function wfSuppressWarnings() in
/var/www/html/w/skins/BlueLL/BlueLL.skin.php:34 Stack trace: #0 /var/www/html/w/
includes/skins/SkinTemplate.php(217): BlueLLTemplate->execute() #1 /var/www/html
/w/includes/OutputPage.php(2574): SkinTemplate->outputPage() #2 /var/www/html/w/
includes/exception/MWExceptionRenderer.php(134): OutputPage->output() #3 /var/ww
w/html/w/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::re
portHTML(Object(Error)) #4 /var/www/html/w/includes/exception/MWExceptionHandler
.php(121): MWExceptionRenderer::output(Object(Error), 2) #5 /var/www/html/w/incl
udes/exception/MWExceptionHandler.php(195): MWExceptionHandler::report(Object(Er
ror)) #6 /var/www/html/w/includes/exception/MWExceptionHandler.php(167): MWExcep
tionHandler::handleException(Object(Error)) #7 [internal function]: MWExceptionH
andler::handleUncaughtException(Object(Error)) #8 {main} thrown in /var/www/html
/w/skins/BlueLL/BlueLL.skin.php on line 34
```

The result came from a clone the BlueLL GitHub. I noticed there are no tagged releases, like `REL1_34` and `REL1_35`. Most Mediawiki skins and extensions provide a tagged release. For example, our [update script](https://github.com/weidai11/website/blob/master/mediawiki/update-wiki.sh) does a `git checkout master -f && git pull` followed by a `git checkout REL1_34`.

Here's what it looks like with BlueLL. Notice BlueLL produces an error *`pathspec 'REL1_34' did not match any file(s) known to git`*.

```
# ./update-wiki.sh
...
Updating /var/www/html/w/skins/CologneBlue/
HEAD is now at 7a30ed7 Localisation updates from https://translatewiki.net.
Already up-to-date.
Already on 'REL1_34'
Updating /var/www/html/w/skins/Vector/
HEAD is now at f39a3f0 vector.js: Remove eager calculation of p-cactions width on page load
Already up-to-date.
Already on 'REL1_34'
Updating /var/www/html/w/skins/BlueLL/
HEAD is now at 9757eb8 T196759: add support for the echo  MW extension
Already up-to-date.
error: pathspec 'REL1_34' did not match any file(s) known to git.
Updating /var/www/html/w/skins/Nimbus/
HEAD is now at 1f1d8a1 Localisation updates from https://translatewiki.net.
Already up-to-date.
Already on 'REL1_34'
...
```

-----

Also see [this issue report for the Pivot Skin](https://www.mediawiki.org/wiki/Topic:Vexujm5qxin5513k). The report says:

<blockquote>The global function `wfSuppressWarnings` was deprecated since 1.26 and now removed. The skin must be updated to use "*.`Wikimedia\AtEase\AtEase::suppressWarnings()</blockquote>

Also see [Pivot Skin Pull Request #90](https://github.com/Hutchy68/pivot/pull/90/files).

I'm guessing that means BlueLL is only available for Mediawiki 1.20 - 1.33. Mediawiki 1.34 and higher is not supported.

### PR DESCRIPTION
**Pull request by jdlrobson**
There are a few exceptions in 1.35 fixed with these small adjustments.
I would like to showcase this on https://skins.wmflabs.org

Fixes: #2

FYI since the skin is not working at time of writing I've also temporarily marked the skin as "unmaintained" on https://www.mediawiki.org/wiki/Skin:BlueLL . Please mark it as stable as soon as this patch is merged.

### CODE REVIEW

**Comment by hugolpz** [comment]
@jdlrobson : so you tested these Skin fixes on a mediawiki you upgraded to 1.35, right ?
We (LL's volunteers) are now discussing accepting your fix. But we have a limited ability to evaluate your work and the risks since we never worked on skins. We do plan to migrate to 1.35+ in March.

Could you comment on this change : [here](https://github.com/lingua-libre/BlueLL/pull/3/commits/7df2c8410af829d4d25780596ad8a12329eb96f3#diff-0bb652c2d848716c9a5d90f45a376bb4b4df772dca045a15d7b0832e6588fd85R75-R80) ?

**Comment by jdlrobson** [comment]
The patch is deployed here: https://skins-demo.wmflabs.org/?useskin=bluell
Without the patch the skin displays a blank screen which should be easy to verify by installing MediaWiki 1.35 and cloning the repo in the skins folder.

No worries about the delay. No expectations my side around timing.

**Comment by hugolpz** [comment]
@Seb35, i believe you have a local instance of LinguaLibre on your PC right ? Could you 1) review this PR, 2) test it on your local instance and 3) validate-merge it when confident enough ?

**Comment by Seb35** [comment]
Yes, I installed a local instance on my PC. I tested quickly this PR this afternoon and it works well on 1.35 together with the [updated extension Custom Subtitle](https://github.com/lingua-libre/CustomSubtitle/pull/2). I see @jdlrobson did a very good job with even the check about RecordWizard for non-LinguaLibre wikis :-) I just review it a bit more extensively next week, particularly to be sure it works on MW 1.31 to deploy it together with upcoming changes from #5.

**Comment by hugolpz** [comment]
Merged. Thank to you both for this work and review. 🧑🏼‍🤝‍🧑🏼 🤝

**Pull request merged**
